### ISSUE TITLE
Blas not found

### ISSUE THREAD

**Issue by roshni-b** [biobakery/homebrew-biobakery#5] opened 2017-06-20 18:54 UTC
File "scipy/integrate/setup.py", line 12, in configuration
    blas_opt = get_info('blas_opt',notfound_action=2)
  File "/home/venkat/.linuxbrew/Cellar/metaphlan2/2.6.0/libexec/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 372, in get_info
    return cl().get_info(notfound_action)
  File "/home/venkat/.linuxbrew/Cellar/metaphlan2/2.6.0/libexec/lib/python2.7/site-packages/numpy/distutils/system_info.py", line 566, in get_info
    raise self.notfounderror(self.notfounderror.__doc__)
numpy.distutils.system_info.BlasNotFoundError: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.

**Comment by ljmciver** [comment] 2017-06-20 23:02
Hello, It looks like you do not have the BLAS libraries installed which are required by scipy (a dependency of metaphlan2). If you can install the BLAS libraries and rerun the metaphlan2 install, it will resolve your error. Alternatively if you would like to install metaphlan2 with out the dependencies (ie scipy, numpy, matplotlib), you can add the following option "$ brew instal metaphlan2 --without-dependencies". Please let me know if you have any questions.

Thank you,
Lauren

**Comment by roshni-b** [comment] 2017-06-21 17:42
Thanks, Lauren. I have installed BLAS now. 
I am getting different errors now: out of memory and bowtie2
```

Error: Out of memory allocating 1073742078 __m128i's for DP matrix: 'std::bad_alloc'
Error: Out of memory allocating 2147484414 __m128i's for DP matrix: 'std::bad_alloc'
Error: Out of memory allocating 1073742127 __m128i's for DP matrix: 'std::bad_alloc'
Error: Encountered exception: 'std::bad_alloc'
Command: /home/venkat/miniconda3/bin/bowtie2-align-s --wrapper basic-0 --quiet --very-sensitive -x /home/venkat/Desktop/Software/biobakery-metaphlan2-c3fb65390c21/db_v20/mpa_v20_m200 -p 4 -f --passthrough -U set3-IIIF1SW-I_S77_finalcontigs.fasta 
(ERR): bowtie2-align exited with value 1
Error while running bowtie2.

```

**Comment by ljmciver** [comment] 2017-06-21 18:40
How much memory is available on your machine? I wonder if you are running out of memory when running metaphlan2. If not, I have seen unexpected behavior when using homebrew and conda. Is it possible to run metaphlan2 outside of conda on your machine?

Thanks!
Lauren

**Comment by ljmciver** [comment] 2017-07-06 19:22
From your other issue post, it looks like you have gotten past the memory issue. I will close this issue. 

Thanks,
Lauren

**Closed** 2017-07-06 19:22 UTC
